### ISSUE TITLE
Request for OkAuthorization fields to be made public

### ISSUE THREAD

**Issue by rahulanand16nov** [3scale-rs/threescalers#88]
After parsing the response from 3scale, there is no way to access the OkAuthorization's fields as their visibility is set to private by default. Either getters or publishing fields would do the trick for accessing them. I can create a PR so, can you please mention which method is favorable?

Reference: https://github.com/3scale-rs/threescalers/blob/c7fb31a2bf064da06197caa7830576b9d80ca3d2/src/response.rs#L111

**Comment by unleashed** [comment]
Definitely best to provide getters - public fields create a usually unneeded and very strong contract for a library. /cc @davidor

**Comment by rahulanand16nov** [comment]
Related PR: #89

**Comment by unleashed** [comment]
Closed via #89.
